### ISSUE TITLE
Error with guzzlehttp/guzzle 7.9.1

### ISSUE THREAD

**Issue by jupiterhs** [RadarsofthouseDev/billwerk-plus-pay-for-magento2#19]
### Preconditions and environment

- Magento version: 2.4.6-p4
- PHP version: 8.1
- radarsofthouse/reepay 1.2.47

### Description

When using guzzlehttp/guzzle 7.9.1 billwerk-plus-pay-for-magento2 throws the below error on checkout 

```
main.CRITICAL: GuzzleHttp\Exception\ConnectException: HTTP/1 is not supported by the cURL handler. in public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:57
```

### Steps to reproduce

1. Make sure that you are on version 7.9.1 of guzzlehttp/guzzle
2. Add a product to cart
3. Go to checkout and fill out the details.
4. Select a billwerk payment gateway and try to checkout
5. Check exception.log for error

### Additional information

Downgrading guzzlehttp/guzzle to 7.8.1 no longer throws the error and checkout works fine.

I noticed in your code that the HTTP protocol is specified at version 1.0
https://github.com/RadarsofthouseDev/billwerk-plus-pay-for-magento2/blob/e20d5299df5f753ab290c3da3eb8ee809eb77390/Client/Api.php#L236

**Comment by RadarsofthouseDev** [comment]
@jupiterhs We have fixed the issue with "guzzlehttp/guzzle" 7.8.2+ and released the new version 1.2.50. Please update the module to the latest version.
