### ISSUE TITLE
Error on setup upgrade

### ISSUE THREAD

**Issue by jupiterhs** [RadarsofthouseDev/billwerk-plus-pay-for-magento2#20]
### Preconditions and environment

- Magento version: 2.4.6-p4
- PHP version: 8.1
- radarsofthouse/reepay 1.2.48

### Description

When running setup upgrade I get the error for etc/config.xml

```
Element 'system': This element is not expected.                                                                                                
  Line: 474    
```

### Additional information

In etc/config.xml a system element is added that is not supported by the schema urn:magento:module:Magento_Store:etc/config.xsd

https://github.com/RadarsofthouseDev/billwerk-plus-pay-for-magento2/blob/e20d5299df5f753ab290c3da3eb8ee809eb77390/etc/config.xml#L474

I think you wanted to add this within default and by mistake it was added outside.

**Comment by RadarsofthouseDev** [comment]
@jupiterhs Thank you for reporting this issue. We have identified the problem with the 'system' element in the etc/config.xml. This issue has been fixed in version 1.2.49
